plugins {
    java
    eclipse
    kotlin("jvm") version "2.3.0"
    id("com.github.johnrengelman.shadow") version "8.1.1"
    // id("com.azuredoom.hytalepublisher") version "1.0.1"  // Requires Java 25 daemon — blocked until plugin targets Java 21
}

group = property("projectGroup") as String
version = property("projectVersion") as String

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
        // vendor.set(JvmVendorSpec.ADOPTIUM)  // Allow any Java 25 vendor
    }
}

repositories {
    // Local Maven repo — provides decompiled Hytale source JARs for jdtls go-to-def.
    // Generated by ~/tools/update-hytale-sources.sh after each decompilation.
    mavenLocal()

    mavenCentral()

    // Official Hytale Maven repository
    // ⚠️ DO NOT add hytale-pre-release repo! It causes version mismatch with decompiled code.
    // The decompile script (~/tools/decompile-hytale.sh) only tracks the release repo.
    // If Gradle resolves a pre-release version, builds will fail with "abstract class" errors.
    maven {
        name = "hytale-release"
        url = uri("https://maven.hytale.com/release")
    }

    // CurseMaven for community mods (HyUI)
    maven {
        name = "cursemaven"
        url = uri("https://www.cursemaven.com")
    }
}

// Enable source attachment download for jdtls LSP (go-to-def on Hytale classes)
eclipse {
    classpath {
        isDownloadSources = true
    }
}

// Hytale Server version - use latest.release for automatic updates from Maven
// This ensures we always build against the newest Hytale API version
val hytaleServerVersion = "latest.release"

// Dependency versions - centralized for easy maintenance
val h2Version = "2.4.240"          // Embedded database (updated 2026-01-24)
val hikariVersion = "7.0.2"        // Connection pooling
val snakeyamlVersion = "2.5"       // YAML parsing (updated 2026-01-24: 2.2 -> 2.5)

// HyUI - Community UI library for cleaner UI development
// CurseForge Project ID: 1431415, File ID: 7626511 (v0.8.7, Feb 15 2026)
val hyuiFileId = "7626511"

// Javet - Java V8 engine (for Vuetale reactive UI framework)
val javetVersion = "4.1.2"

// Test dependency versions
val junitVersion = "5.14.2"        // JUnit Jupiter (updated 2026-01-24: 5.10.1 -> 5.14.2)
val mockitoVersion = "5.21.0"      // Mockito (updated 2026-01-24: 5.8.0 -> 5.21.0)

dependencies {
    // Hytale Server API (from official Maven repository)
    compileOnly("com.hypixel.hytale:Server:$hytaleServerVersion")

    // HyUI - Fluent UI builder library (bundled - provides HTML/CSS-like UI syntax)
    // Docs: docs/HyUI/ | Discord: https://discord.gg/NYeK9JqmNB
    implementation("curse.maven:hyui-1431415:$hyuiFileId")

    // ===== DATABASE DEPENDENCIES =====
    // Database connection pooling - Bundle for standalone operation
    implementation("com.zaxxer:HikariCP:$hikariVersion")

    // H2 embedded database - Bundle for default/standalone operation
    // Updated 2026-01-24: 2.2.224 -> 2.4.240 (bug fixes, performance, security)
    implementation("com.h2database:h2:$h2Version")

    // External database drivers - compileOnly (user provides if needed)
    compileOnly("com.mysql:mysql-connector-j:8.2.0")
    compileOnly("org.postgresql:postgresql:42.7.1")

    // Vuetale - Vue 3 reactive UI framework for Hytale (Kelpy's compiled JAR)
    implementation(files("libs/vuetale-1.0.12-preview.jar"))

    // Utilities
    compileOnly("com.google.code.gson:gson:2.10.1")  // Hytale provides
    implementation("org.yaml:snakeyaml:$snakeyamlVersion")  // Bundle - we use directly

    // Annotations (compile-time only)
    compileOnly("com.google.code.findbugs:jsr305:3.0.2")
    compileOnly("javax.annotation:javax.annotation-api:1.3.2")

    // Logging - SLF4J API provided by Hytale, but HikariCP logs to SLF4J at runtime
    // Include no-op provider to silence "no SLF4J provider found" warnings from HikariCP
    compileOnly("org.slf4j:slf4j-api:2.0.9")
    implementation("org.slf4j:slf4j-nop:2.0.9")

    // Testing (test scope only)
    testImplementation("com.hypixel.hytale:Server:$hytaleServerVersion")  // Needed for Hytale API mocking
    testImplementation("org.yaml:snakeyaml:$snakeyamlVersion")  // Needed for tests (bundled at runtime)
    testImplementation("com.zaxxer:HikariCP:$hikariVersion")  // Needed for database tests
    testImplementation("com.h2database:h2:$h2Version")  // Needed for database tests (embedded)
    testImplementation("com.google.flogger:flogger:0.8")  // Needed for FluentLogger mocking
    testImplementation("org.junit.jupiter:junit-jupiter:$junitVersion")
    testImplementation("org.mockito:mockito-core:$mockitoVersion")
    testImplementation("org.mockito:mockito-inline:5.2.0")  // Enable mocking final classes (deprecated in 5.x, kept for compatibility)
    testImplementation("org.mockito:mockito-junit-jupiter:$mockitoVersion")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Resolve the actual Hytale Server version from compileClasspath (lazy — only computed at execution time)
val hytaleResolvedVersion = provider {
    configurations.compileClasspath.get()
        .resolvedConfiguration
        .resolvedArtifacts
        .find { it.moduleVersion.id.group == "com.hypixel.hytale" }
        ?.moduleVersion?.id?.version ?: "*"
}

tasks {
    processResources {
        inputs.property("hytaleVersion", hytaleResolvedVersion)
        filesMatching("**/manifest.json") {
            filter { line -> line.replace("@HYTALE_VERSION@", hytaleResolvedVersion.get()) }
        }

        // Bundle Voile wiki content into JAR resources.
        // Source lives in Wiki/content/ (single source of truth).
        // Voile's UniversalDocumentationLoader auto-discovers Common/Docs/ from mod JARs.
        // Excludes images/ (web wiki only, 37MB) and meta.json (HytaleModding.dev metadata).
        from("Wiki/content") {
            into("Common/Docs")
            exclude("**/images/**")
            exclude("**/meta.json")
        }
    }

    shadowJar {
        archiveClassifier.set("")

        // Clean up manifest
        manifest {
            attributes(
                "Implementation-Title" to project.name,
                "Implementation-Version" to project.version,
                "Multi-Release" to "true"
            )
        }

        // Include asset pack at JAR root level.
        // Hytale's asset loader expects Server/ and Common/ at the JAR root
        // when IncludesAssetPack is true in manifest.json.
        // Without this, assets end up nested under hytale-assets/ which Hytale ignores.
        // Exclude the asset pack's own manifest.json — our plugin manifest at root already
        // declares IncludesAssetPack:true, and the asset pack manifest would overwrite it
        // (replacing the Main class entry, causing a classloader NPE on startup).
        from("src/main/resources/hytale-assets") {
            exclude("manifest.json")
        }

        // Remove the nested hytale-assets/ copy from the JAR (assets are at root now).
        // The nested copy still exists in build/resources/main/ for deploy.sh compatibility.
        exclude("hytale-assets/**")

        // Exclude signature files (cause issues)
        exclude("META-INF/*.SF")
        exclude("META-INF/*.DSA")
        exclude("META-INF/*.RSA")
        exclude("META-INF/LICENSE*")
        exclude("META-INF/NOTICE*")

        // NOTE: Relocation disabled - Shadow plugin's ASM doesn't support Java 25 bytecode
        // SnakeYAML is bundled without relocation. If conflicts occur with other plugins,
        // consider using a different config library or waiting for Shadow plugin update.
    }

    build {
        dependsOn(shadowJar)
    }

    test {
        useJUnitPlatform()
        testLogging {
            events("passed", "skipped", "failed")
            showStandardStreams = true
        }
        // Enable experimental Byte Buddy support for Java 25
        // Set HytaleLogManager before any logging classes are loaded
        jvmArgs(
            "-Dnet.bytebuddy.experimental=true",
            "-Djava.util.logging.manager=com.hypixel.hytale.logger.backend.HytaleLogManager"
        )
    }

    compileJava {
        options.encoding = "UTF-8"
        options.release.set(25)
        options.compilerArgs.addAll(listOf(
            "-Xlint:all",
            "-Xlint:-serial",
            "-Xlint:-processing"
        ))
    }

    jar {
        enabled = false // Only use shadowJar
    }


    // Custom task to copy built JAR to Hytale server mods directory.
    // Set HYTALE_SERVER_DIR environment variable to your server location.
    register<Copy>("deployPlugin") {
        dependsOn(shadowJar)
        from("build/libs/${project.name}-${project.version}.jar")

        val serverDir = System.getenv("HYTALE_SERVER_DIR")
            ?: throw GradleException(
                "HYTALE_SERVER_DIR environment variable is not set.\n" +
                "Set it to your Hytale server directory, e.g.:\n" +
                "  Windows:  set HYTALE_SERVER_DIR=C:\\path\\to\\HytaleServer\n" +
                "  Linux:    export HYTALE_SERVER_DIR=/path/to/HytaleServer"
            )
        val modsDir = File(serverDir, "mods").absolutePath
        into(modsDir)

        doLast {
            println("Deployed ${project.name}-${project.version}.jar to $modsDir")
        }
    }

    // Verify Java toolchain version
    register("verifyJavaVersion") {
        doLast {
            val javaVersion = JavaVersion.current()
            val toolchainService = project.extensions.getByType<JavaToolchainService>()
            val toolchainVersion = toolchainService
                .launcherFor(java.toolchain)
                .get()
                .metadata
                .languageVersion

            println("Build Java Version: $javaVersion")
            println("Toolchain Java Version: $toolchainVersion")
            println("✅ Using Java ${toolchainVersion.asInt()} toolchain for compilation")
        }
    }

    // Show resolved Hytale Server version (useful when using latest.release)
    register("showHytaleVersion") {
        doLast {
            val resolved = configurations.compileClasspath.get()
                .resolvedConfiguration
                .resolvedArtifacts
                .find { it.moduleVersion.id.group == "com.hypixel.hytale" }
            if (resolved != null) {
                println("Hytale Server version: ${resolved.moduleVersion.id.version}")
            } else {
                println("Hytale Server dependency not found in classpath")
            }
        }
    }
}

// Balance simulation runner — uses real calculation classes with game configs
// Usage: ./gradlew simulate
tasks.register<JavaExec>("simulate") {
    classpath = sourceSets.test.get().runtimeClasspath
    mainClass.set("io.github.larsonix.trailoforbis.simulation.SimulationMain")
    workingDir = projectDir
    jvmArgs(
        "-Djava.util.logging.manager=com.hypixel.hytale.logger.backend.HytaleLogManager"
    )
    args(layout.buildDirectory.dir("simulation-output").get().asFile.absolutePath)
    dependsOn("testClasses")
    // Must use Java 25 toolchain (classes compiled with Java 25, Gradle daemon uses 21)
    javaLauncher.set(javaToolchains.launcherFor {
        languageVersion.set(JavaLanguageVersion.of(25))
    })
    // Show stdout/stderr from the simulation process
    standardOutput = System.out
    errorOutput = System.err
}

// Debug tool for investigating specific mob/combat scenarios
// Usage: ./gradlew simulateDebug
tasks.register<JavaExec>("simulateDebug") {
    classpath = sourceSets.test.get().runtimeClasspath
    mainClass.set("io.github.larsonix.trailoforbis.simulation.debug.MobStatDebug")
    workingDir = projectDir
    jvmArgs(
        "-Djava.util.logging.manager=com.hypixel.hytale.logger.backend.HytaleLogManager"
    )
    dependsOn("testClasses")
    javaLauncher.set(javaToolchains.launcherFor {
        languageVersion.set(JavaLanguageVersion.of(25))
    })
    standardOutput = System.out
    errorOutput = System.err
}

kotlin {
    jvmToolchain(25)
}

// ─── Platform Publishing (CurseForge, ModTale, Modifold) ───
// HytalePublisher plugin (com.azuredoom.hytalepublisher) provides ./gradlew publishAll
// BLOCKED: Plugin compiled targeting Java 25 but Gradle daemon runs Java 21.
//          Kotlin DSL breaks on Java 25 daemon. Ask AzureDoom to target Java 21.
//          Until then, platform uploads use the release.yml GitHub Action workflow.
//
// When unblocked, uncomment the plugin in plugins {} and this config:
//
// hytalePublisher {
//     version.set(project.version.toString())
//     releaseType.set("release")
//     gameVersion.set("2026.+")
//     changelogFile.set("CHANGELOG.md")
//
//     modtale {
//         enabled = true
//         projectId = ""  // Set after creating ModTale project
//     }
//     curseforge {
//         enabled = true
//         projectId = ""  // Set after creating CurseForge project
//     }
//     modifold {
//         enabled = true
//         projectId = ""  // Set after creating Modifold project
//     }
// }
