config.yml: 1
ailments.yml: 1
combat-text.yml: 1
container-loot.yml: 1
death-recap.yml: 1
entity-discovery.yml: 1
equipment-stats.yml: 1
gear-balance.yml: 1
gear-modifiers.yml: 1
hexcode-items.yml: 1
hexcode-spells.yml: 1
inventory-detection.yml: 1
leveling.yml: 1
loot-discovery.yml: 1
loot-filter.yml: 1
loot-items.yml: 1
mob-archetypes.yml: 1
mob-classification.yml: 1
mob-elements.yml: 1
mob-rarity.yml: 1
mob-resistances.yml: 1
mob-scaling.yml: 1
mob-spawn.yml: 1
mob-stat-pool.yml: 1
party.yml: 1
realm-mobs.yml: 1
realm-modifiers.yml: 1
realms.yml: 1
skill-sanctum.yml: 1
skill-tree-hexcode.yml: 1
skill-tree-layout.yml: 1
skill-tree-positions.yml: 1
skill-tree.yml: 1
tooltip.yml: 1
vanilla-conversion.yml: 1
