package io.github.larsonix.trailoforbis.gear.item;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Common interface for RPG custom item data types that need dynamic registration.
 *
 * <p>Implemented by:
 * <ul>
 *   <li>{@code RealmMapData} - Realm map items with modifiers</li>
 * </ul>
 *
 * <p>Note: Stones are now native Hytale items defined in the asset pack
 * and no longer implement this interface.
 *
 * <p>This interface allows the item registration and sync systems to handle
 * custom items uniformly while preserving type-specific data.
 *
 * <h2>Instance IDs</h2>
 * <p>Each custom item has a unique instance ID generated by
 * {@link CustomItemInstanceId}. Items with instance IDs are registered as
 * unique items in Hytale's asset map, allowing custom names and tooltips.
 *
 * <h2>Usage</h2>
 * <pre>{@code
 * // Check if item has an instance ID (for registration)
 * if (customItemData.hasInstanceId()) {
 *     String itemId = customItemData.getItemId();
 *     // Register with ItemRegistryService
 * }
 *
 * // Get display info
 * String name = customItemData.getDisplayName();
 * String desc = customItemData.getDescription();
 * }</pre>
 *
 * @see CustomItemInstanceId
 * @see ItemRegistryService
 */
public interface CustomItemData {

    /**
     * Gets the unique instance ID for this item.
     *
     * <p>The instance ID is used to generate a unique Hytale item ID
     * that allows per-instance custom names and tooltips.
     *
     * @return null if not registered
     */
    @Nullable
    CustomItemInstanceId getInstanceId();

    /**
     * Checks if this item has a valid instance ID.
     *
     * <p>Items without instance IDs cannot be registered for custom display.
     *
     * @return true if the item has an instance ID
     */
    default boolean hasInstanceId() {
        return getInstanceId() != null;
    }

    /**
     * Gets the Hytale item ID for this custom item.
     *
     * <p>This is the ID used in {@code UpdateItems} packets and asset map
     * registration. Format: {@code rpg_{type}_{timestamp}_{counter}}
     *
     * @return e.g. "rpg_map_1706123456789_0", or null if no instance ID
     */
    @Nullable
    default String getItemId() {
        CustomItemInstanceId id = getInstanceId();
        return id != null ? id.toItemId() : null;
    }

    /**
     * Gets the base Hytale item ID that this custom item is derived from.
     *
     * <p>This is the vanilla Hytale item that provides the model, texture,
     * and default behavior. Examples:
     * <ul>
     *   <li>Maps: "Objective_Treasure_Map"</li>
     *   <li>Stones: "Ingredient_Crystal_Blue"</li>
     * </ul>
     *
     * @return e.g. "Objective_Treasure_Map"
     */
    @Nonnull
    String getBaseItemId();

    /**
     * Gets the display name for this item.
     *
     * <p>This is the custom name shown in the player's inventory and tooltips.
     * Should be color-formatted with rarity colors where appropriate.
     *
     */
    @Nonnull
    String getDisplayName();

    /**
     * Gets the description/lore for this item.
     *
     * <p>This is the tooltip text shown below the item name.
     * Can include multiple lines separated by newlines.
     *
     */
    @Nonnull
    String getDescription();

    /**
     * Gets the item type for instance ID generation.
     *
     * @return The item type (e.g., "map", "stone")
     */
    @Nonnull
    CustomItemInstanceId.ItemType getItemType();
}
