package io.github.larsonix.trailoforbis.mobs.stats;

import io.github.larsonix.trailoforbis.attributes.ComputedStats;

/**
 * Immutable snapshot of all computed combat stats for a scaled mob.
 *
 * <p>Generated by {@link MobStatGenerator}, this record holds the final values for health,
 * damage, armor, elemental stats, AI parameters, and more. Can be converted to
 * {@link io.github.larsonix.trailoforbis.attributes.ComputedStats} for use in the damage pipeline.
 */
public record MobStatProfile(
        int mobLevel,
        double totalPool,
        double maxHealth,
        double physicalDamage,
        double armor,
        double moveSpeed,
        double attackSpeed,
        double attackRange,
        double attackCooldown,
        double criticalChance,
        double criticalMultiplier,
        double dodgeChance,
        double blockChance,
        double parryChance,
        double lifeSteal,
        double healthRegen,
        double fireDamage,
        double waterDamage,
        double lightningDamage,
        double voidDamage,
        double fireResistance,
        double waterResistance,
        double lightningResistance,
        double voidResistance,
        double firePenetration,
        double waterPenetration,
        double lightningPenetration,
        double voidPenetration,
        double fireIncreasedDamage,
        double waterIncreasedDamage,
        double lightningIncreasedDamage,
        double voidIncreasedDamage,
        double fireMoreDamage,
        double waterMoreDamage,
        double lightningMoreDamage,
        double voidMoreDamage,
        double aggroRange,
        double reactionDelay,
        double chargeTime,
        double chargeDistance,
        double armorPenetration,
        double trueDamage,
        double accuracy,
        double knockbackResistance,
        long seed
) {
    public static final MobStatProfile UNSCALED = new MobStatProfile(
            1, 0.0, 50.0, 5.0, 0.0, 1.0, 1.0, 2.0, 1.0, 5.0, 150.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, // fire/cold/lightning/chaos penetration (none)
            0.0, 0.0, 0.0, 0.0, // fire/cold/lightning/chaos increased damage (none)
            0.0, 0.0, 0.0, 0.0, // fire/cold/lightning/chaos more damage (none)
            16.0, 1.0, 1.0, 5.0, 0.0, 0.0,
            100.0,  // accuracy (base 100)
            0.0,    // knockbackResistance (none)
            0L
    );

    public double getScaledDamage(double baseDamage) {
        return baseDamage * physicalDamage;
    }

    public double getEffectiveDamage(double baseDamage, boolean isCritical) {
        double dmg = baseDamage * physicalDamage;
        if (isCritical) {
            dmg *= criticalMultiplier / 100.0;
        }
        dmg += fireDamage + waterDamage + lightningDamage + voidDamage;
        return dmg;
    }

    public double getEffectiveCooldown(double baseCooldown) {
        return baseCooldown / attackSpeed;
    }

    public double getEffectiveRange(double baseRange) {
        return baseRange + attackRange;
    }

    public double getEffectiveArmor() {
        return armor * (1.0 - armorPenetration / 100.0);
    }

    public double getTotalElementalDamage() {
        return fireDamage + waterDamage + lightningDamage + voidDamage;
    }

    public double getTotalElementalResistance() {
        return (fireResistance + waterResistance + lightningResistance + voidResistance) / 4.0;
    }

    public ComputedStats toComputedStats() {
        return ComputedStats.builder()
                .maxHealth((float) maxHealth)
                .physicalDamage((float) physicalDamage)
                .armor((float) armor)
                .movementSpeedPercent((float) ((moveSpeed - 1.0) * 100.0))
                .attackSpeedPercent((float) ((attackSpeed - 1.0) * 100.0))
                .criticalChance((float) criticalChance)
                .criticalMultiplier((float) criticalMultiplier)
                .evasion((float) dodgeChance)
                .passiveBlockChance((float) blockChance)
                .parryChance((float) parryChance)
                .lifeSteal((float) lifeSteal)
                .armorPenetration((float) armorPenetration)
                .trueDamage((float) trueDamage)
                .healthRegen((float) healthRegen)
                .fireDamage((float) fireDamage)
                .waterDamage((float) waterDamage)
                .lightningDamage((float) lightningDamage)
                .voidDamage((float) voidDamage)
                .fireResistance((float) fireResistance)
                .waterResistance((float) waterResistance)
                .lightningResistance((float) lightningResistance)
                .voidResistance((float) voidResistance)
                .firePenetration((float) firePenetration)
                .waterPenetration((float) waterPenetration)
                .lightningPenetration((float) lightningPenetration)
                .voidPenetration((float) voidPenetration)
                .fireDamagePercent((float) fireIncreasedDamage)
                .waterDamagePercent((float) waterIncreasedDamage)
                .lightningDamagePercent((float) lightningIncreasedDamage)
                .voidDamagePercent((float) voidIncreasedDamage)
                .fireDamageMultiplier((float) fireMoreDamage)
                .waterDamageMultiplier((float) waterMoreDamage)
                .lightningDamageMultiplier((float) lightningMoreDamage)
                .voidDamageMultiplier((float) voidMoreDamage)
                .accuracy((float) accuracy)
                .knockbackResistance((float) knockbackResistance)
                .build();
    }

    public MobStatProfile withBossMultiplier(double multiplier) {
        return new MobStatProfile(
                mobLevel, totalPool * multiplier,
                maxHealth * multiplier, physicalDamage * multiplier, armor * multiplier,
                moveSpeed, attackSpeed, attackRange, attackCooldown,
                criticalChance, criticalMultiplier,
                dodgeChance, blockChance, parryChance,
                lifeSteal, healthRegen * multiplier,
                fireDamage, waterDamage, lightningDamage, voidDamage,
                fireResistance, waterResistance, lightningResistance, voidResistance,
                firePenetration, waterPenetration, lightningPenetration, voidPenetration,
                fireIncreasedDamage, waterIncreasedDamage, lightningIncreasedDamage, voidIncreasedDamage,
                fireMoreDamage, waterMoreDamage, lightningMoreDamage, voidMoreDamage,
                aggroRange, reactionDelay, chargeTime, chargeDistance,
                armorPenetration, trueDamage,
                accuracy, knockbackResistance,
                seed
        );
    }

    public MobStatProfile withEliteMultiplier(double multiplier) {
        return withBossMultiplier(multiplier);
    }

    public boolean isScaled() {
        return mobLevel > 1 || totalPool > 0;
    }

    public int getEffectivePower() {
        return (int) (mobLevel + (totalPool / 10.0));
    }

    @Override
    public String toString() {
        return String.format(
                "MobStatProfile{lv=%d, pool=%.0f, hp=%.0f, dmg=%.0f, armor=%.0f, spd=%.2f, crit=%.0f%%/%.0f%%}",
                mobLevel, totalPool, maxHealth, physicalDamage, armor, moveSpeed,
                criticalChance, criticalMultiplier
        );
    }
}
