package io.github.larsonix.trailoforbis.mobs.model;

import io.github.larsonix.trailoforbis.attributes.ComputedStats;
import io.github.larsonix.trailoforbis.elemental.ElementType;
import io.github.larsonix.trailoforbis.elemental.ElementalStats;
import io.github.larsonix.trailoforbis.mobs.archetype.MobArchetype;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Immutable stat container for a scaled mob.
 *
 * <p>Generated by {@code MobStatFactory} using Template + Noise distribution.
 * Each stat traces back to a clear design decision: pool → archetype ratio →
 * conversion factor → noise.
 *
 * <p><b>33 stats total:</b>
 * <ul>
 *   <li>Core (5): maxHealth, physicalDamage, armor, accuracy, moveSpeed</li>
 *   <li>Offensive (5): critChance, critMultiplier, armorPenetration, lifeSteal, trueDamage</li>
 *   <li>Defensive (2): evasion, knockbackResistance</li>
 *   <li>Elemental (18): 6× resistance, 6× damage, 6× penetration (in ElementalStats)</li>
 *   <li>Sustain (1): healthRegen</li>
 *   <li>Ailment (2): ailmentThresholdMultiplier, ailmentEffectiveness</li>
 * </ul>
 *
 * <p>Integrates with the combat system through {@link #toComputedStats()}.
 */
public record MobStats(
    int level,
    double totalPool,
    // Core
    double maxHealth,
    double physicalDamage,
    double armor,
    double moveSpeed,
    double accuracy,
    // Offensive
    double criticalChance,
    double criticalMultiplier,
    double armorPenetration,
    double lifeSteal,
    double trueDamage,
    // Defensive
    double evasion,
    double knockbackResistance,
    // Sustain
    double healthRegen,
    // Ailment
    double ailmentThresholdMultiplier,
    double ailmentEffectiveness,
    // Elemental
    @Nullable ElementalStats elementalStats,
    // Combat identity — determines whether base damage converts to elemental
    @Nullable MobArchetype archetype
) {
    /** Default stats for unscaled mobs (level 1, no pool). */
    public static final MobStats UNSCALED = new MobStats(
        1, 0.0,
        50.0,   // maxHealth
        5.0,    // physicalDamage
        0.0,    // armor
        1.0,    // moveSpeed
        100.0,  // accuracy
        5.0,    // criticalChance
        150.0,  // criticalMultiplier
        0.0,    // armorPenetration
        0.0,    // lifeSteal
        0.0,    // trueDamage
        0.0,    // evasion
        0.0,    // knockbackResistance
        0.0,    // healthRegen
        1.0,    // ailmentThresholdMultiplier (1.0 = threshold equals maxHP)
        1.0,    // ailmentEffectiveness (1.0 = full ailment effect)
        null,   // elementalStats
        null    // archetype (unscaled = no archetype)
    );

    /**
     * Converts to ComputedStats for the damage pipeline.
     *
     * <p><b>Note:</b> {@code physicalDamage} is NOT forwarded as {@code flatPhysicalDamage}.
     * Mob physical damage enters the pipeline via Hytale's vanilla damage event —
     * {@code MobScalingSystem} modifies attack damage via EntityStatMap modifiers.
     * Forwarding it here would double-count.
     *
     * <p><b>Damage type conversion (spell/physical split):</b> CASTER archetype mobs
     * with a detected element get 100% damage conversion to their primary element.
     * This means the calculator's Step 3 (applyConversion) moves their physical base
     * into the elemental slot, where only element-specific resistance reduces it —
     * armor has no effect. This implements the core design: physical base → armor defends,
     * elemental base → resistance defends.
     */
    @Nonnull
    public ComputedStats toComputedStats() {
        ComputedStats.Builder builder = ComputedStats.builder()
            .mobStats(true)
            // Core — physicalDamage intentionally NOT forwarded (comes via vanilla event)
            .maxHealth((float) maxHealth)
            .armor((float) armor)
            .movementSpeedPercent((float) ((moveSpeed - 1.0) * 100.0))
            .accuracy((float) accuracy)
            // Offensive
            .criticalChance((float) criticalChance)
            .criticalMultiplier((float) criticalMultiplier)
            .armorPenetration((float) armorPenetration)
            .lifeSteal((float) lifeSteal)
            .trueDamage((float) trueDamage)
            // Defensive
            .evasion((float) evasion)
            .knockbackResistance((float) knockbackResistance)
            // Sustain
            .healthRegen((float) healthRegen);

        // Forward ALL 6 elements — damage, resistance, and penetration
        if (elementalStats != null) {
            for (ElementType element : ElementType.values()) {
                float damage = (float) elementalStats.getFlatDamage(element);
                float resistance = (float) elementalStats.getResistance(element);
                float penetration = (float) elementalStats.getPenetration(element);

                if (damage != 0) {
                    switch (element) {
                        case FIRE -> builder.fireDamage(damage);
                        case WATER -> builder.waterDamage(damage);
                        case LIGHTNING -> builder.lightningDamage(damage);
                        case EARTH -> builder.earthDamage(damage);
                        case WIND -> builder.windDamage(damage);
                        case VOID -> builder.voidDamage(damage);
                    }
                }
                if (resistance != 0) {
                    switch (element) {
                        case FIRE -> builder.fireResistance(resistance);
                        case WATER -> builder.waterResistance(resistance);
                        case LIGHTNING -> builder.lightningResistance(resistance);
                        case EARTH -> builder.earthResistance(resistance);
                        case WIND -> builder.windResistance(resistance);
                        case VOID -> builder.voidResistance(resistance);
                    }
                }
                if (penetration != 0) {
                    switch (element) {
                        case FIRE -> builder.firePenetration(penetration);
                        case WATER -> builder.waterPenetration(penetration);
                        case LIGHTNING -> builder.lightningPenetration(penetration);
                        case EARTH -> builder.earthPenetration(penetration);
                        case WIND -> builder.windPenetration(penetration);
                        case VOID -> builder.voidPenetration(penetration);
                    }
                }
            }
        }

        // Caster mobs convert their physical base damage to their primary element.
        // The calculator's Step 3 (applyConversion) uses these fields to move damage
        // from the physical slot into the elemental slot, where armor doesn't apply.
        if (archetype == MobArchetype.CASTER && elementalStats != null) {
            ElementType primaryElement = elementalStats.getPrimaryElement();
            if (primaryElement != null) {
                switch (primaryElement) {
                    case FIRE -> builder.fireConversion(100f);
                    case WATER -> builder.waterConversion(100f);
                    case LIGHTNING -> builder.lightningConversion(100f);
                    case EARTH -> builder.earthConversion(100f);
                    case WIND -> builder.windConversion(100f);
                    case VOID -> builder.voidConversion(100f);
                }
            }
        }

        return builder.build();
    }

    /**
     * Creates a copy with rarity multiplier applied.
     *
     * <p>Only flat combat stats are multiplied. Percentage-based stats (crit chance,
     * evasion, life steal, armor pen) stay fixed. Ailment fields stay fixed.
     * Elemental stats are copied as-is.
     */
    @Nonnull
    public MobStats withMultiplier(double multiplier) {
        return new MobStats(
            level, totalPool * multiplier,
            maxHealth * multiplier,
            physicalDamage * multiplier,
            armor * multiplier,
            moveSpeed,
            accuracy,
            criticalChance,
            criticalMultiplier,
            armorPenetration,
            lifeSteal,
            trueDamage * multiplier,
            evasion,
            knockbackResistance,
            healthRegen * multiplier,
            ailmentThresholdMultiplier,
            ailmentEffectiveness,
            elementalStats != null ? elementalStats.copy() : null,
            archetype
        );
    }

    public boolean isScaled() {
        return level > 1 || totalPool > 0;
    }

    public int getEffectivePower() {
        return (int) (level + (totalPool / 10.0));
    }

    @Override
    public String toString() {
        return String.format(
            "MobStats{lv=%d, pool=%.0f, hp=%.0f, dmg=%.0f, arm=%.0f, spd=%.2f, " +
            "eva=%.0f, acc=%.0f, crit=%.0f%%/%.0f%%, steal=%.0f%%, pen=%.0f%%, " +
            "regen=%.1f/s, true=%.0f, kbRes=%.0f%%, ailThr=%.1f, ailEff=%.1f}",
            level, totalPool, maxHealth, physicalDamage, armor, moveSpeed,
            evasion, accuracy, criticalChance, criticalMultiplier,
            lifeSteal, armorPenetration, healthRegen, trueDamage,
            knockbackResistance, ailmentThresholdMultiplier, ailmentEffectiveness
        );
    }

    public String toShortString() {
        return String.format("Lv%d HP%.0f DMG%.0f ARM%.0f SPD%.2f", level, maxHealth, physicalDamage, armor, moveSpeed);
    }

    // ==================== Elemental Convenience Methods ====================

    public boolean hasElementalDamage() {
        return elementalStats != null && elementalStats.hasAnyElementalDamage();
    }

    @Nullable
    public ElementType getPrimaryElement() {
        return elementalStats != null ? elementalStats.getPrimaryElement() : null;
    }

    @Nonnull
    public ElementalStats getElementalStatsOrEmpty() {
        return elementalStats != null ? elementalStats : new ElementalStats();
    }

    @Nonnull
    public MobStats withElementalStats(@Nullable ElementalStats elemental) {
        return new MobStats(
            level, totalPool, maxHealth, physicalDamage, armor, moveSpeed, accuracy,
            criticalChance, criticalMultiplier, armorPenetration, lifeSteal, trueDamage,
            evasion, knockbackResistance, healthRegen,
            ailmentThresholdMultiplier, ailmentEffectiveness, elemental,
            archetype
        );
    }

    // Per-element convenience getters for backward compat
    public double getFireDamage() { return elementalStats != null ? elementalStats.getFlatDamage(ElementType.FIRE) : 0; }
    public double getWaterDamage() { return elementalStats != null ? elementalStats.getFlatDamage(ElementType.WATER) : 0; }
    public double getLightningDamage() { return elementalStats != null ? elementalStats.getFlatDamage(ElementType.LIGHTNING) : 0; }
    public double getVoidDamage() { return elementalStats != null ? elementalStats.getFlatDamage(ElementType.VOID) : 0; }
    public double getFireResistance() { return elementalStats != null ? elementalStats.getResistance(ElementType.FIRE) : 0; }
    public double getWaterResistance() { return elementalStats != null ? elementalStats.getResistance(ElementType.WATER) : 0; }
    public double getLightningResistance() { return elementalStats != null ? elementalStats.getResistance(ElementType.LIGHTNING) : 0; }
    public double getVoidResistance() { return elementalStats != null ? elementalStats.getResistance(ElementType.VOID) : 0; }
    public double getFirePenetration() { return elementalStats != null ? elementalStats.getPenetration(ElementType.FIRE) : 0; }
    public double getWaterPenetration() { return elementalStats != null ? elementalStats.getPenetration(ElementType.WATER) : 0; }
    public double getLightningPenetration() { return elementalStats != null ? elementalStats.getPenetration(ElementType.LIGHTNING) : 0; }
    public double getVoidPenetration() { return elementalStats != null ? elementalStats.getPenetration(ElementType.VOID) : 0; }
}
