package io.github.larsonix.trailoforbis.loot.container;

import com.hypixel.hytale.logger.HytaleLogger;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.inventory.container.ItemContainer;

import io.github.larsonix.trailoforbis.gear.conversion.ItemClassifier;
import io.github.larsonix.trailoforbis.gear.conversion.ItemClassifier.Classification;
import io.github.larsonix.trailoforbis.gear.conversion.ItemClassifier.ItemType;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.*;
import java.util.UUID;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Core algorithm for replacing vanilla container loot with RPG items.
 *
 * <p>This class handles the actual container content manipulation:
 * <ul>
 *   <li>Scans container contents using {@link ItemClassifier}</li>
 *   <li>Removes vanilla weapons and armor (per config rules)</li>
 *   <li>Preserves materials, consumables, and tools (per config rules)</li>
 *   <li>Adds RPG loot generated by {@link ContainerLootGenerator}</li>
 * </ul>
 *
 * <h2>Replacement Algorithm</h2>
 * <ol>
 *   <li>Classify all items in the container</li>
 *   <li>Build removal list (weapons/armor to remove)</li>
 *   <li>Build preservation list (items to keep)</li>
 *   <li>Generate RPG loot for empty slots</li>
 *   <li>Apply changes atomically via replaceAll</li>
 * </ol>
 *
 * <h2>Thread Safety</h2>
 * <p>This class is thread-safe as it's stateless. Container modifications
 * should still be performed on the world thread.
 *
 * @see ContainerLootGenerator
 * @see ContainerTracker
 */
public final class ContainerLootReplacer {

    private static final HytaleLogger LOGGER = HytaleLogger.forEnclosingClass();

    private final ContainerLootConfig config;
    private final ContainerLootGenerator lootGenerator;
    private final ItemClassifier itemClassifier;
    private final ContainerTierClassifier tierClassifier;

    /**
     * Creates a new container loot replacer.
     *
     * @param config         The container loot configuration
     * @param lootGenerator  The loot generator for creating RPG items
     * @param itemClassifier The item classifier for detecting gear
     * @param tierClassifier The tier classifier for container bonus lookup
     */
    public ContainerLootReplacer(
            @Nonnull ContainerLootConfig config,
            @Nonnull ContainerLootGenerator lootGenerator,
            @Nonnull ItemClassifier itemClassifier,
            @Nonnull ContainerTierClassifier tierClassifier) {
        this.config = Objects.requireNonNull(config, "config cannot be null");
        this.lootGenerator = Objects.requireNonNull(lootGenerator, "lootGenerator cannot be null");
        this.itemClassifier = Objects.requireNonNull(itemClassifier, "itemClassifier cannot be null");
        this.tierClassifier = Objects.requireNonNull(tierClassifier, "tierClassifier cannot be null");
    }

    // =========================================================================
    // MAIN REPLACEMENT
    // =========================================================================

    /**
     * Replaces vanilla loot in a container with RPG items.
     *
     * <p>This method:
     * <ol>
     *   <li>Scans all slots and classifies items</li>
     *   <li>Removes vanilla weapons/armor per config</li>
     *   <li>Preserves materials/consumables/tools per config</li>
     *   <li>Generates and adds RPG loot to empty slots</li>
     * </ol>
     *
     * @param container   The container to modify
     * @param playerLevel The opening player's level (for loot scaling)
     * @param tier        The container tier (for loot bonuses)
     * @param playerId    The opening player's UUID (for rarity bonus calculation)
     * @return Result containing statistics about the replacement
     */
    @Nonnull
    public ReplacementResult replace(
            @Nonnull ItemContainer container,
            int playerLevel,
            @Nonnull ContainerTier tier,
            @Nonnull UUID playerId) {

        Objects.requireNonNull(container, "container cannot be null");
        Objects.requireNonNull(tier, "tier cannot be null");
        Objects.requireNonNull(playerId, "playerId cannot be null");

        // Step 1: Analyze container contents
        ContainerAnalysis analysis = analyzeContainer(container);

        if (config.getAdvanced().isDebugLogging()) {
            LOGGER.atInfo().log("Container analysis: %d slots, %d weapons, %d armor, %d other",
                analysis.totalSlots, analysis.weaponSlots.size(),
                analysis.armorSlots.size(), analysis.otherSlots.size());
        }

        // Step 2: Build the new slot contents
        Map<Short, ItemStack> newContents = buildNewContents(analysis, playerLevel, tier, playerId);

        // Step 3: Apply changes via replaceAll
        int removed = applyReplacements(container, analysis, newContents);

        int added = (int) newContents.values().stream()
            .filter(item -> item != null && !ItemStack.isEmpty(item))
            .count();

        if (config.getAdvanced().isDebugLogging()) {
            LOGGER.atInfo().log("Replacement complete: removed %d items, added %d RPG items",
                removed, added);
        }

        return new ReplacementResult(
            removed,
            added,
            analysis.preservedCount,
            tier
        );
    }

    // =========================================================================
    // TOTAL REPLACEMENT (Realm Mode)
    // =========================================================================

    /**
     * Completely replaces ALL container contents with RPG items.
     *
     * <p>Unlike {@link #replace}, which selectively removes weapons/armor and
     * preserves other items, this method:
     * <ol>
     *   <li>Clears every slot in the container</li>
     *   <li>Rolls a target item count from the tier's min/max range, capped at capacity</li>
     *   <li>Generates RPG loot (gear, stones, maps) to fill those slots</li>
     *   <li>Shuffles placement across the container for visual variety</li>
     * </ol>
     *
     * <p>Used when {@code clear_all_vanilla: true} for realm containers where
     * no vanilla items should remain.
     *
     * @param container   The container to completely replace
     * @param playerLevel The opening player's level (for loot scaling)
     * @param tier        The container tier (for loot bonuses and item count)
     * @param playerId    The opening player's UUID (for rarity bonus)
     * @return Result containing statistics about the replacement
     */
    @Nonnull
    public ReplacementResult replaceTotal(
            @Nonnull ItemContainer container,
            int playerLevel,
            @Nonnull ContainerTier tier,
            @Nonnull UUID playerId) {

        Objects.requireNonNull(container, "container cannot be null");
        Objects.requireNonNull(tier, "tier cannot be null");
        Objects.requireNonNull(playerId, "playerId cannot be null");

        short capacity = container.getCapacity();
        if (capacity <= 0) {
            return new ReplacementResult(0, 0, 0, tier);
        }

        // Count existing items for stats (before clearing)
        int existingItems = 0;
        for (short slot = 0; slot < capacity; slot++) {
            ItemStack item = container.getItemStack(slot);
            if (item != null && !ItemStack.isEmpty(item)) {
                existingItems++;
            }
        }

        // Roll target item count from tier range, capped at container capacity
        int[] itemRange = tierClassifier.getItemRange(tier);
        int minItems = itemRange[0];
        int maxItems = itemRange[1];
        int targetCount = minItems == maxItems ? minItems
            : minItems + ThreadLocalRandom.current().nextInt(maxItems - minItems + 1);
        targetCount = Math.min(targetCount, capacity);

        // Generate RPG loot to fill target slots
        List<ItemStack> rpgLoot = lootGenerator.generateLootForSlots(playerLevel, tier, playerId, targetCount);

        // Clear the entire container
        container.replaceAll((slot, existing) -> null);

        // Build shuffled slot list for visual variety
        List<Short> allSlots = new ArrayList<>(capacity);
        for (short s = 0; s < capacity; s++) {
            allSlots.add(s);
        }
        Collections.shuffle(allSlots, ThreadLocalRandom.current());

        // Place RPG items in shuffled slots
        int placed = 0;
        for (int i = 0; i < rpgLoot.size() && i < allSlots.size(); i++) {
            container.setItemStackForSlot(allSlots.get(i), rpgLoot.get(i));
            placed++;
        }

        if (config.getAdvanced().isDebugLogging()) {
            LOGGER.atInfo().log("Total replacement: cleared %d items, placed %d RPG items in %d-slot container (tier: %s)",
                existingItems, placed, capacity, tier);
        }

        return new ReplacementResult(existingItems, placed, 0, tier);
    }

    // =========================================================================
    // ANALYSIS
    // =========================================================================

    /**
     * Analyzes container contents and classifies all items.
     *
     * @param container The container to analyze
     * @return Analysis result with categorized slots
     */
    @Nonnull
    private ContainerAnalysis analyzeContainer(@Nonnull ItemContainer container) {
        short capacity = container.getCapacity();
        List<Short> weaponSlots = new ArrayList<>();
        List<Short> armorSlots = new ArrayList<>();
        List<Short> otherSlots = new ArrayList<>();
        List<Short> emptySlots = new ArrayList<>();
        int preservedCount = 0;

        ContainerLootConfig.ItemRemoval removalConfig = config.getItemRemoval();

        for (short slot = 0; slot < capacity; slot++) {
            ItemStack itemStack = container.getItemStack(slot);

            if (itemStack == null || ItemStack.isEmpty(itemStack)) {
                emptySlots.add(slot);
                continue;
            }

            Classification classification = itemClassifier.classify(itemStack);
            String itemId = itemStack.getItemId();

            // Check explicit preserved/removed lists first
            if (isExplicitlyPreserved(itemId, removalConfig)) {
                otherSlots.add(slot);
                preservedCount++;
                continue;
            }

            if (isExplicitlyRemoved(itemId, removalConfig)) {
                // Treat as weapon for removal tracking
                weaponSlots.add(slot);
                continue;
            }

            // Classify based on item type
            switch (classification.type()) {
                case WEAPON -> {
                    if (removalConfig.isRemoveWeapons()) {
                        weaponSlots.add(slot);
                    } else {
                        otherSlots.add(slot);
                        preservedCount++;
                    }
                }
                case ARMOR -> {
                    if (removalConfig.isRemoveArmor()) {
                        armorSlots.add(slot);
                    } else {
                        otherSlots.add(slot);
                        preservedCount++;
                    }
                }
                case OTHER -> {
                    // Check if this is a material, consumable, or tool
                    if (shouldPreserveOtherItem(itemId, removalConfig)) {
                        otherSlots.add(slot);
                        preservedCount++;
                    } else {
                        // Unknown item type - preserve by default
                        otherSlots.add(slot);
                        preservedCount++;
                    }
                }
            }
        }

        return new ContainerAnalysis(
            capacity,
            weaponSlots,
            armorSlots,
            otherSlots,
            emptySlots,
            preservedCount
        );
    }

    /**
     * Checks if an item ID is explicitly preserved by config.
     */
    private boolean isExplicitlyPreserved(@Nonnull String itemId,
                                          @Nonnull ContainerLootConfig.ItemRemoval config) {
        List<String> preserved = config.getPreservedItems();
        if (preserved == null || preserved.isEmpty()) {
            return false;
        }
        return preserved.stream().anyMatch(pattern -> matchesPattern(itemId, pattern));
    }

    /**
     * Checks if an item ID is explicitly removed by config.
     */
    private boolean isExplicitlyRemoved(@Nonnull String itemId,
                                        @Nonnull ContainerLootConfig.ItemRemoval config) {
        List<String> removed = config.getRemovedItems();
        if (removed == null || removed.isEmpty()) {
            return false;
        }
        return removed.stream().anyMatch(pattern -> matchesPattern(itemId, pattern));
    }

    /**
     * Checks if an "other" item should be preserved based on config.
     *
     * <p>Currently preserves all non-weapon/non-armor items by default.
     * Future: Could add heuristics for materials vs consumables vs tools.
     */
    private boolean shouldPreserveOtherItem(@Nonnull String itemId,
                                            @Nonnull ContainerLootConfig.ItemRemoval config) {
        // For now, preserve all non-gear items
        // Future enhancement: detect materials/consumables/tools by item ID patterns
        return config.isPreserveMaterials() ||
               config.isPreserveConsumables() ||
               config.isPreserveTools();
    }

    /**
     * Simple wildcard pattern matching.
     *
     * @param value   The value to match
     * @param pattern The pattern (supports * wildcard)
     * @return true if the value matches the pattern
     */
    private boolean matchesPattern(@Nonnull String value, @Nonnull String pattern) {
        if (pattern.equals("*")) {
            return true;
        }
        if (!pattern.contains("*")) {
            return value.equalsIgnoreCase(pattern);
        }

        // Convert wildcard to regex
        String regex = "^" + pattern.replace("*", ".*") + "$";
        return value.matches("(?i)" + regex);
    }

    // =========================================================================
    // CONTENT BUILDING
    // =========================================================================

    /**
     * Builds the new container contents map.
     *
     * @param analysis    The container analysis
     * @param playerLevel The player's level
     * @param tier        The container tier
     * @return Map of slot -> new ItemStack (null for preserved items)
     */
    @Nonnull
    private Map<Short, ItemStack> buildNewContents(
            @Nonnull ContainerAnalysis analysis,
            int playerLevel,
            @Nonnull ContainerTier tier,
            @Nonnull UUID playerId) {

        Map<Short, ItemStack> contents = new HashMap<>();

        // Mark slots to clear (weapons and armor to remove)
        for (Short slot : analysis.weaponSlots) {
            contents.put(slot, null); // Will be cleared
        }
        for (Short slot : analysis.armorSlots) {
            contents.put(slot, null); // Will be cleared
        }

        // Generate RPG loot (with player rarity bonus from WIND attribute)
        List<ItemStack> rpgLoot = lootGenerator.generateLoot(playerLevel, tier, playerId);

        // Calculate available slots (cleared + empty)
        List<Short> availableSlots = new ArrayList<>();
        availableSlots.addAll(analysis.weaponSlots);
        availableSlots.addAll(analysis.armorSlots);
        availableSlots.addAll(analysis.emptySlots);

        // Place RPG loot in available slots
        int lootIndex = 0;
        for (Short slot : availableSlots) {
            if (lootIndex >= rpgLoot.size()) {
                // No more loot to place, leave slot empty
                if (!contents.containsKey(slot)) {
                    contents.put(slot, null);
                }
            } else {
                contents.put(slot, rpgLoot.get(lootIndex));
                lootIndex++;
            }
        }

        // Log if we couldn't place all loot
        if (lootIndex < rpgLoot.size()) {
            LOGGER.atWarning().log("Could not place %d RPG items - container full",
                rpgLoot.size() - lootIndex);
        }

        return contents;
    }

    // =========================================================================
    // APPLICATION
    // =========================================================================

    /**
     * Applies the replacement changes to the container.
     *
     * @param container   The container to modify
     * @param analysis    The container analysis
     * @param newContents The new slot contents
     * @return Number of items removed
     */
    private int applyReplacements(
            @Nonnull ItemContainer container,
            @Nonnull ContainerAnalysis analysis,
            @Nonnull Map<Short, ItemStack> newContents) {

        int removedCount = analysis.weaponSlots.size() + analysis.armorSlots.size();

        // Use replaceAll for atomic modification
        container.replaceAll((slot, existing) -> {
            if (newContents.containsKey(slot)) {
                return newContents.get(slot); // May be null to clear, or new item
            }
            return existing; // Preserve original
        });

        return removedCount;
    }

    // =========================================================================
    // RESULT TYPES
    // =========================================================================

    /**
     * Result of a container replacement operation.
     *
     * @param itemsRemoved    Number of vanilla items removed
     * @param itemsAdded      Number of RPG items added
     * @param itemsPreserved  Number of items preserved (materials, etc.)
     * @param tier            The container tier used
     */
    public record ReplacementResult(
        int itemsRemoved,
        int itemsAdded,
        int itemsPreserved,
        @Nonnull ContainerTier tier
    ) {
        /**
         * Gets a summary string for logging.
         *
         * @return Human-readable summary
         */
        @Nonnull
        public String summary() {
            return String.format("Removed %d, added %d, preserved %d (tier: %s)",
                itemsRemoved, itemsAdded, itemsPreserved, tier);
        }
    }

    /**
     * Analysis of container contents before replacement.
     */
    private record ContainerAnalysis(
        int totalSlots,
        @Nonnull List<Short> weaponSlots,
        @Nonnull List<Short> armorSlots,
        @Nonnull List<Short> otherSlots,
        @Nonnull List<Short> emptySlots,
        int preservedCount
    ) {}
}
